name: Test nsis-install

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: [x86, amd64]

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install NSIS
        uses: ./    # use ./action.yml
        with:
          arch: ${{matrix.arch}}
