name: Test nsis-install

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: [x86, amd64]

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install NSIS
        id: install
        if: runner.os == 'Windows'
        uses: ./    # use ./action.yml
        with:
          arch: ${{matrix.arch}}

      - name: Install NSIS (non-Windows)
        if: runner.os != 'Windows'
        uses: ./
        continue-on-error: true # expect failure
        with:
          arch: ${{matrix.arch}}

      - name: Install outputs
        if: runner.os == 'Windows'
        env:
          NSIS_INSTDIR: ${{steps.install.outputs.instdir}}
          NSIS_VERSION: ${{steps.install.outputs.version}}
        shell: python
        run: |
          import os
          print(f'-- NSIS_INSTDIR = {os.getenv("NSIS_INSTDIR")}')
          print(f'-- NSIS_VERSION = {os.getenv("NSIS_VERSION")}')
